use std::path::PathBuf;

use crate::session::SessionId;

/// In-memory snapshot of shared state across all friring instances.
///
/// Used for computing deltas between local and database state.
#[derive(Debug, Clone)]
pub struct SharedState {
    /// Session counter for unique naming across instances.
    pub session_counter: usize,

    /// Active sessions across all instances.
    pub sessions: Vec<SharedSession>,
}

impl SharedState {
    /// Create a new empty shared state.
    pub fn new() -> Self {
        Self {
            session_counter: 0,
            sessions: Vec::new(),
        }
    }
}

impl Default for SharedState {
    fn default() -> Self {
        Self::new()
    }
}

/// A session known to the shared state.
///
/// Tracks essential metadata needed for all instances to see and adopt sessions.
#[derive(Clone)]
pub struct SharedSession {
    /// Unique session identifier (generated by spawning instance).
    pub id: SessionId,

    /// Human-readable session name (e.g., "1", "Session 1").
    pub name: String,

    /// Coding agent driving this session (e.g., "claude", "codex").
    pub agent: String,

    /// Backend identifier for finding the session in tmux.
    /// Format: "friring:@0" for local tmux sessions.
    pub backend_id: String,

    /// Backend type (e.g., "tmux").
    pub backend_type: String,

    /// The underlying agent session ID (if started).
    pub agent_session_id: Option<String>,

    pub cwd: Option<PathBuf>,

    /// Extra directories (beyond `cwd`) this session spans. When a session has
    /// more than one member dir, the agent is launched in a per-session symlink
    /// workspace gathering them all (see `crate::workspace`), so every agent —
    /// not just those with an `--add-dir`-style flag — can reach them.
    pub additional_dirs: Vec<PathBuf>,

    /// User-chosen directory for the multi-repo symlink workspace (local
    /// sessions only); `None` = the default id-derived path under the
    /// workspaces root. See `SessionInfo::workspace_dir`.
    pub workspace_dir: Option<PathBuf>,

    pub worktrees: Vec<SharedWorktree>,

    /// Backend ID of the companion shell pane (if spawned).
    pub shell_backend_id: Option<String>,

    /// Sandbox profile the agent runs under (`docs/SANDBOX.md`); `None` for an
    /// unsandboxed session. A policy backend leaves `backend_type` alone — the
    /// boundary is invisible to the session layer — so this is the only record
    /// of it, and the only way a restart re-derives the same wrapper.
    pub sandbox_profile: Option<String>,

    /// Whether the last launch actually put that boundary in force
    /// (`sessions.sandbox_unenforced`). The profile says what the session asked
    /// for; this says what it got, and is what stops a restored or adopted
    /// session wearing the shield over an agent running on the host.
    ///
    /// [`Unrecorded`](crate::session::SandboxEnforcement::Unrecorded) is **not**
    /// "applied": it means the writer has no launch to report, and
    /// [`upsert_session`](crate::storage::Database::upsert_session) leaves the
    /// stored verdict alone rather than clearing it.
    pub sandbox_enforcement: crate::session::SandboxEnforcement,

    /// Parent session (lead/worker relationship for orchestration).
    /// `None` for top-level sessions. Purely informational: deleting the
    /// parent does not cascade to children.
    pub parent_session_id: Option<SessionId>,

    /// Manual position in the session list. `None` = never moved: renders
    /// after all ordered sessions, in creation order.
    pub display_order: Option<i64>,

    /// The exact multiplexer window this session's agent runs in
    /// ([`MuxIdentity`](crate::session::MuxIdentity)), so every destructive
    /// action can revalidate before it acts. Written by the launch that
    /// recorded it; a writer with nothing recorded leaves the stored identity
    /// alone, exactly as it leaves the sandbox verdict alone.
    pub mux: crate::session::MuxIdentity,

    /// Where this session's egress proxy listened and the credential it
    /// demanded, so a restart can rebind the **same** endpoint with the **same**
    /// token — a running agent already holds URLs naming both.
    ///
    /// The token is kept here and deliberately **not** on
    /// [`SessionInfo`](crate::session::SessionInfo): that type is rendered,
    /// serialized and logged all over the app, and the safest redaction is the
    /// value never being in it. Storage reads this only where restoration needs
    /// it, and `Debug` withholds it.
    pub egress: crate::session::EgressRecord,

    /// The narrowed effective policy a bridge child was launched under, as
    /// JSON. `None` for every session that is not one.
    pub sandbox_overlay: Option<String>,

    /// Tombstone flag: true if this session was soft-deleted.
    /// Soft-deleted sessions are excluded from active listings.
    pub tombstone: bool,

    /// Timestamp when this session was tombstoned (millis since epoch).
    pub tombstone_at: Option<u64>,
}

impl std::fmt::Debug for SharedSession {
    /// Hand-written so [`crate::session::EgressRecord`]'s token never reaches a log
    /// line.
    ///
    /// The same reasoning as
    /// [`ProxyGrant`](crate::sandbox::ProxyGrant)'s: this struct is the one that
    /// *holds* a running boundary's credential, and a derived `Debug` puts it in
    /// every tracing field and failing assertion that mentions a session. The
    /// nested record's own `Debug` does the withholding, so this is the ordinary
    /// field list with nothing special about it — which is the point.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SharedSession")
            .field("id", &self.id)
            .field("name", &self.name)
            .field("agent", &self.agent)
            .field("backend_id", &self.backend_id)
            .field("backend_type", &self.backend_type)
            .field("agent_session_id", &self.agent_session_id)
            .field("cwd", &self.cwd)
            .field("additional_dirs", &self.additional_dirs)
            .field("workspace_dir", &self.workspace_dir)
            .field("worktrees", &self.worktrees)
            .field("shell_backend_id", &self.shell_backend_id)
            .field("sandbox_profile", &self.sandbox_profile)
            .field("sandbox_enforcement", &self.sandbox_enforcement)
            .field("parent_session_id", &self.parent_session_id)
            .field("display_order", &self.display_order)
            .field("mux", &self.mux)
            .field("egress", &self.egress)
            .field("sandbox_overlay", &self.sandbox_overlay)
            .field("tombstone", &self.tombstone)
            .field("tombstone_at", &self.tombstone_at)
            .finish()
    }
}

/// Worktree information embedded in shared session.
#[derive(Debug, Clone, PartialEq)]
pub struct SharedWorktree {
    /// Path to the git repository root.
    pub repo_path: PathBuf,

    pub worktree_path: PathBuf,

    pub branch: String,
}

impl From<crate::session::WorktreeInfo> for SharedWorktree {
    fn from(wt: crate::session::WorktreeInfo) -> Self {
        Self {
            repo_path: wt.repo_path,
            worktree_path: wt.worktree_path,
            branch: wt.branch,
        }
    }
}

impl From<SharedWorktree> for crate::session::WorktreeInfo {
    fn from(wt: SharedWorktree) -> Self {
        Self {
            repo_path: wt.repo_path,
            worktree_path: wt.worktree_path,
            branch: wt.branch,
        }
    }
}

/// Get current time in milliseconds since Unix epoch.
pub fn current_time_millis() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_shared_state_is_empty_and_valid() {
        let state = SharedState::new();
        assert_eq!(state.session_counter, 0);
        assert!(state.sessions.is_empty());
    }

    #[test]
    fn default_state_equals_new() {
        let new_state = SharedState::new();
        let default_state = SharedState::default();
        assert_eq!(new_state.session_counter, default_state.session_counter);
    }

    #[test]
    fn worktree_info_to_shared_worktree() {
        let wt = crate::session::WorktreeInfo {
            repo_path: PathBuf::from("/repo"),
            worktree_path: PathBuf::from("/repo/.git/wt/feat"),
            branch: "feat".to_string(),
        };

        let shared: SharedWorktree = wt.into();
        assert_eq!(shared.repo_path, PathBuf::from("/repo"));
        assert_eq!(shared.worktree_path, PathBuf::from("/repo/.git/wt/feat"));
        assert_eq!(shared.branch, "feat");
    }

    #[test]
    fn shared_worktree_to_worktree_info() {
        let shared = SharedWorktree {
            repo_path: PathBuf::from("/repo"),
            worktree_path: PathBuf::from("/repo/.git/wt/feat"),
            branch: "feat".to_string(),
        };

        let wt: crate::session::WorktreeInfo = shared.into();
        assert_eq!(wt.repo_path, PathBuf::from("/repo"));
        assert_eq!(wt.worktree_path, PathBuf::from("/repo/.git/wt/feat"));
        assert_eq!(wt.branch, "feat");
    }
}
