#!/usr/bin/env bash
# proposals.sh — the forge agent's proposal store. JSONL is the source of
# truth (proposals.jsonl); proposals.md is a human-readable render kept in sync
# on every mutation.
#
# Subcommands:
#   upsert --slug S --title T --why W --command C [--kind automation|extension]
#       Insert or update an OPEN proposal by slug. Preserves an existing
#       proposal's status/created (so applied/dismissed ones are never
#       resurrected) while refreshing its title/why/command/kind.
#   list [--all]        List open proposals (or all, with status).
#   apply <slug>        Run the proposal's stored command (must start with
#                       `friring-cli`), then mark it applied. Prints the
#                       command output.
#   dismiss <slug>      Mark a proposal dismissed (won't resurface on scans).
#   render              Regenerate proposals.md from proposals.jsonl.
#
# A record: {slug,title,kind,why,command,status,created}
#   status ∈ {open, applied, dismissed}

set -euo pipefail

HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
HOME_DIR="$(CDPATH= cd -- "$HERE/.." && pwd)"
STORE="$HOME_DIR/proposals.jsonl"
RENDER="$HOME_DIR/proposals.md"

src() { [ -f "$STORE" ] && printf '%s' "$STORE" || printf '/dev/null'; }

# is_single_friring_cli COMMAND
# True iff COMMAND is exactly one `friring-cli` invocation: its first word is
# `friring-cli` AND it contains no shell command-chaining (`;`, `&`, `|`,
# newline) or command/process substitution (`$(...)`, backticks, `<(...)`,
# `>(...)`) *outside* of quotes. A prefix match alone is not enough — `sh -c`
# would happily run a second, arbitrary command chained after a `friring-cli `
# prefix. The scan is quote-aware so a legitimately quoted argument (e.g.
# `--prompt "do a; then b"`) is still allowed; only operators that would let
# `sh` execute *another* program are rejected.
is_single_friring_cli() {
  local s=$1 n i ch nxt state=none bs=$'\\'
  [ "${s%%[[:space:]]*}" = "friring-cli" ] || return 1
  n=${#s}
  for (( i = 0; i < n; i++ )); do
    ch=${s:i:1}
    nxt=${s:i+1:1}
    case "$state" in
      single)
        [ "$ch" = "'" ] && state=none
        ;;
      double)
        if [ "$ch" = '"' ]; then state=none
        elif [ "$ch" = "$bs" ]; then i=$(( i + 1 ))    # escaped char, skip
        elif [ "$ch" = '`' ]; then return 1            # backtick subst (active in "")
        elif [ "$ch" = '$' ] && [ "$nxt" = '(' ]; then return 1
        fi
        ;;
      *)  # outside quotes
        case "$ch" in
          "'") state=single ;;
          '"') state=double ;;
          "$bs") i=$(( i + 1 )) ;;                       # escaped char, skip
          ';'|'&'|'|') return 1 ;;                      # chaining
          '`') return 1 ;;                              # command substitution
          '$') [ "$nxt" = '(' ] && return 1 ;;          # $(...) substitution
          '<'|'>') [ "$nxt" = '(' ] && return 1 ;;      # <(...)/>(...) process subst
          *) [ "$ch" = $'\n' ] && return 1 ;;           # newline separates commands
        esac
        ;;
    esac
  done
  [ "$state" = none ] || return 1                        # unterminated quote → suspect
  return 0
}

render() {
  {
    echo "# Forge proposals"
    echo
    echo "Generated by the forge agent — review, then apply with:"
    echo
    echo '```bash'
    echo "$HERE/proposals.sh apply <slug>"
    echo '```'
    echo
    OPEN="$(jq -s '[.[] | select(.status=="open")]' "$(src)" 2>/dev/null || echo '[]')"
    if [ "$(printf '%s' "$OPEN" | jq 'length')" = "0" ]; then
      echo "_No open proposals._"
    else
      echo "## Open"
      echo
      printf '%s' "$OPEN" | jq -r '.[] |
        "### \(.title)  `\(.slug)`",
        "",
        "- kind: \(.kind)",
        "- why: \(.why)",
        "",
        "```bash",
        .command,
        "```",
        ""'
    fi
    DONE="$(jq -s '[.[] | select(.status!="open")]' "$(src)" 2>/dev/null || echo '[]')"
    if [ "$(printf '%s' "$DONE" | jq 'length')" != "0" ]; then
      echo "## Applied / dismissed"
      echo
      printf '%s' "$DONE" | jq -r '.[] | "- [\(.status)] `\(.slug)` — \(.title)"'
    fi
  } > "$RENDER"
}

cmd="${1:-}"; shift || true
case "$cmd" in
  upsert)
    SLUG="" TITLE="" WHY="" COMMAND="" KIND="automation"
    while [ $# -gt 0 ]; do
      case "$1" in
        --slug)    SLUG="$2"; shift 2 ;;
        --title)   TITLE="$2"; shift 2 ;;
        --why)     WHY="$2"; shift 2 ;;
        --command) COMMAND="$2"; shift 2 ;;
        --kind)    KIND="$2"; shift 2 ;;
        *) echo "unknown flag: $1" >&2; exit 2 ;;
      esac
    done
    [ -n "$SLUG" ] && [ -n "$TITLE" ] && [ -n "$COMMAND" ] || {
      echo "upsert needs --slug, --title, --command" >&2; exit 2; }
    NOW="$(date +%s)"
    jq -nc --slurpfile cur "$(src)" \
      --arg slug "$SLUG" --arg title "$TITLE" --arg why "$WHY" \
      --arg command "$COMMAND" --arg kind "$KIND" --argjson now "$NOW" '
      ($cur | map(select(.slug==$slug)) | .[0]) as $prev
      | ($cur | map(select(.slug!=$slug)))
        + [{slug:$slug, title:$title, kind:$kind, why:$why, command:$command,
            status:($prev.status // "open"), created:($prev.created // $now)}]
      | .[]' > "$STORE.tmp"
    mv "$STORE.tmp" "$STORE"
    render
    echo "upserted $SLUG"
    ;;
  list)
    [ "${1:-}" = "--all" ] && FILTER='.' || FILTER='select(.status=="open")'
    if [ -f "$STORE" ]; then
      jq -r "$FILTER | \"  \(.slug)  [\(.status)]  \(.title)\"" "$STORE" 2>/dev/null
    fi
    ;;
  apply)
    SLUG="${1:-}"; [ -n "$SLUG" ] || { echo "apply needs <slug>" >&2; exit 2; }
    [ -f "$STORE" ] || { echo "no proposals yet" >&2; exit 1; }
    REC="$(jq -c --arg s "$SLUG" 'select(.slug==$s)' "$STORE" | head -1)"
    [ -n "$REC" ] || { echo "no such proposal: $SLUG" >&2; exit 1; }
    CMD="$(printf '%s' "$REC" | jq -r '.command')"
    if ! is_single_friring_cli "$CMD"; then
      echo "refusing to run command that is not a single 'friring-cli ...' invocation: $CMD" >&2
      exit 3
    fi
    echo "+ $CMD"
    # `if` exempts the assignment from `set -e`, so a failing command does not
    # abort the script before we capture its status and run the graceful path.
    if OUT="$(sh -c "$CMD")"; then rc=0; else rc=$?; fi
    printf '%s\n' "$OUT"
    [ "$rc" -eq 0 ] || { echo "command failed (rc=$rc); leaving proposal open" >&2; exit "$rc"; }
    jq -c --arg s "$SLUG" 'if .slug==$s then .status="applied" else . end' "$STORE" > "$STORE.tmp"
    mv "$STORE.tmp" "$STORE"
    render
    echo "applied $SLUG"
    ;;
  dismiss)
    SLUG="${1:-}"; [ -n "$SLUG" ] || { echo "dismiss needs <slug>" >&2; exit 2; }
    [ -f "$STORE" ] || { echo "no proposals yet" >&2; exit 1; }
    jq -c --arg s "$SLUG" 'if .slug==$s then .status="dismissed" else . end' "$STORE" > "$STORE.tmp"
    mv "$STORE.tmp" "$STORE"
    render
    echo "dismissed $SLUG"
    ;;
  render)
    render; echo "rendered $RENDER"
    ;;
  *)
    echo "usage: proposals.sh {upsert|list|apply|dismiss|render} ..." >&2
    exit 2
    ;;
esac
